AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{PROJECT_NAME}} - {{PROJECT_DESCRIPTION}}

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12
    Architectures:
      - x86_64
    Environment:
      Variables:
        SECRET_NAME: {{PROJECT_NAME}}/prod
        AWS_REGION_NAME: {{AWS_REGION}}

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - dev
    Description: Deployment environment

Resources:
  # Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "{{PROJECT_NAME}}-${Environment}"
      CodeUri: backend/
      Handler: src.handler.lambda_handler
      Description: "{{PROJECT_DESCRIPTION}}"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:{{AWS_REGION}}:${AWS::AccountId}:secret:{{PROJECT_NAME}}/*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            RestApiId: !Ref ApiGateway
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ApiGateway
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "{{PROJECT_NAME}}-api-${Environment}"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.{{AWS_REGION}}.amazonaws.com/${Environment}/"

  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn

  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref ApiFunction
